In [3]:
import pandas as pd

data = pd.read_csv (r'yellow_tripdata_2021-01.csv') 
print (data)

         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0             1.0  2021-01-01 00:30:10   2021-01-01 00:36:12              1.0
1             1.0  2021-01-01 00:51:20   2021-01-01 00:52:19              1.0
2             1.0  2021-01-01 00:43:30   2021-01-01 01:11:06              1.0
3             1.0  2021-01-01 00:15:48   2021-01-01 00:31:01              0.0
4             2.0  2021-01-01 00:31:49   2021-01-01 00:48:21              1.0
...           ...                  ...                   ...              ...
1369760       NaN  2021-01-25 08:32:04   2021-01-25 08:49:32              NaN
1369761       NaN  2021-01-25 08:34:00   2021-01-25 09:04:00              NaN
1369762       NaN  2021-01-25 08:37:00   2021-01-25 08:53:00              NaN
1369763       NaN  2021-01-25 08:28:00   2021-01-25 08:50:00              NaN
1369764       NaN  2021-01-25 08:38:00   2021-01-25 08:50:00              NaN

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 2.10         1.0                  N           142
1                 0.20         1.0                  N           238
2                14.70         1.0                  N           132
3                10.60         1.0                  N           138
4                 4.94         1.0                  N            68
...                ...         ...                ...           ...
1369760           8.80         NaN                NaN           135
1369761           5.86         NaN                NaN            42
1369762           4.45         NaN                NaN            14
1369763          10.04         NaN                NaN           175
1369764           4.93         NaN                NaN           248

         DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
0                  43           2.0         8.00   3.00      0.5        0.00
1                 151           2.0         3.00   0.50      0.5        0.00
2                 165           1.0        42.00   0.50      0.5        8.65
3                 132           1.0        29.00   0.50      0.5        6.05
4                  33           1.0        16.50   0.50      0.5        4.06
...               ...           ...          ...    ...      ...         ...
1369760            82           NaN        21.84   2.75      0.5        0.00
1369761           161           NaN        26.67   2.75      0.5        0.00
1369762           106           NaN        25.29   2.75      0.5        0.00
1369763           216           NaN        28.24   2.75      0.5        0.00
1369764           168           NaN        20.76   2.75      0.5        0.00

         tolls_amount  improvement_surcharge  total_amount  \
0                 0.0                    0.3         11.80
1                 0.0                    0.3          4.30
2                 0.0                    0.3         51.95
3                 0.0                    0.3         36.35
4                 0.0                    0.3         24.36
...               ...                    ...           ...
1369760           0.0                    0.3         25.39
1369761           0.0                    0.3         30.22
1369762           0.0                    0.3         28.84
1369763           0.0                    0.3         31.79
1369764           0.0                    0.3         24.31

         congestion_surcharge
0                         2.5
1                         0.0
2                         0.0
3                         0.0
4                         2.5
...                       ...
1369760                   0.0
1369761                   0.0
1369762                   0.0
1369763                   0.0
1369764                   0.0

[1369765 rows x 18 columns]

/Users/kiranbagwe/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [11]:
#print(data["tpep_pickup_datetime"])
#print(data["tpep_dropoff_datetime"])

data["pickuptime"] = pd.to_datetime(data["tpep_pickup_datetime"])
print(data["pickuptime"])
data["droptime"] = pd.to_datetime(data["tpep_dropoff_datetime"])
print(data["droptime"])

print(data)

0         2021-01-01 00:30:10
1         2021-01-01 00:51:20
2         2021-01-01 00:43:30
3         2021-01-01 00:15:48
4         2021-01-01 00:31:49
                  ...
1369760   2021-01-25 08:32:04
1369761   2021-01-25 08:34:00
1369762   2021-01-25 08:37:00
1369763   2021-01-25 08:28:00
1369764   2021-01-25 08:38:00
Name: pickuptime, Length: 1369765, dtype: datetime64[ns]
0         2021-01-01 00:36:12
1         2021-01-01 00:52:19
2         2021-01-01 01:11:06
3         2021-01-01 00:31:01
4         2021-01-01 00:48:21
                  ...
1369760   2021-01-25 08:49:32
1369761   2021-01-25 09:04:00
1369762   2021-01-25 08:53:00
1369763   2021-01-25 08:50:00
1369764   2021-01-25 08:50:00
Name: droptime, Length: 1369765, dtype: datetime64[ns]
         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0             1.0  2021-01-01 00:30:10   2021-01-01 00:36:12              1.0
1             1.0  2021-01-01 00:51:20   2021-01-01 00:52:19              1.0
2             1.0  2021-01-01 00:43:30   2021-01-01 01:11:06              1.0
3             1.0  2021-01-01 00:15:48   2021-01-01 00:31:01              0.0
4             2.0  2021-01-01 00:31:49   2021-01-01 00:48:21              1.0
...           ...                  ...                   ...              ...
1369760       NaN  2021-01-25 08:32:04   2021-01-25 08:49:32              NaN
1369761       NaN  2021-01-25 08:34:00   2021-01-25 09:04:00              NaN
1369762       NaN  2021-01-25 08:37:00   2021-01-25 08:53:00              NaN
1369763       NaN  2021-01-25 08:28:00   2021-01-25 08:50:00              NaN
1369764       NaN  2021-01-25 08:38:00   2021-01-25 08:50:00              NaN

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 2.10         1.0                  N           142
1                 0.20         1.0                  N           238
2                14.70         1.0                  N           132
3                10.60         1.0                  N           138
4                 4.94         1.0                  N            68
...                ...         ...                ...           ...
1369760           8.80         NaN                NaN           135
1369761           5.86         NaN                NaN            42
1369762           4.45         NaN                NaN            14
1369763          10.04         NaN                NaN           175
1369764           4.93         NaN                NaN           248

         DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
0                  43           2.0         8.00   3.00      0.5        0.00
1                 151           2.0         3.00   0.50      0.5        0.00
2                 165           1.0        42.00   0.50      0.5        8.65
3                 132           1.0        29.00   0.50      0.5        6.05
4                  33           1.0        16.50   0.50      0.5        4.06
...               ...           ...          ...    ...      ...         ...
1369760            82           NaN        21.84   2.75      0.5        0.00
1369761           161           NaN        26.67   2.75      0.5        0.00
1369762           106           NaN        25.29   2.75      0.5        0.00
1369763           216           NaN        28.24   2.75      0.5        0.00
1369764           168           NaN        20.76   2.75      0.5        0.00

         tolls_amount  improvement_surcharge  total_amount  \
0                 0.0                    0.3         11.80
1                 0.0                    0.3          4.30
2                 0.0                    0.3         51.95
3                 0.0                    0.3         36.35
4                 0.0                    0.3         24.36
...               ...                    ...           ...
1369760           0.0                    0.3         25.39
1369761           0.0                    0.3         30.22
1369762           0.0                    0.3         28.84
1369763           0.0                    0.3         31.79
1369764           0.0                    0.3         24.31

         congestion_surcharge          pickuptime            droptime
0                         2.5 2021-01-01 00:30:10 2021-01-01 00:36:12
1                         0.0 2021-01-01 00:51:20 2021-01-01 00:52:19
2                         0.0 2021-01-01 00:43:30 2021-01-01 01:11:06
3                         0.0 2021-01-01 00:15:48 2021-01-01 00:31:01
4                         2.5 2021-01-01 00:31:49 2021-01-01 00:48:21
...                       ...                 ...                 ...
1369760                   0.0 2021-01-25 08:32:04 2021-01-25 08:49:32
1369761                   0.0 2021-01-25 08:34:00 2021-01-25 09:04:00
1369762                   0.0 2021-01-25 08:37:00 2021-01-25 08:53:00
1369763                   0.0 2021-01-25 08:28:00 2021-01-25 08:50:00
1369764                   0.0 2021-01-25 08:38:00 2021-01-25 08:50:00

[1369765 rows x 20 columns]

In [13]:
data["difference_in_time"] = data["droptime"] - data["pickuptime"]
print(data["difference_in_time"])

0         0 days 00:06:02
1         0 days 00:00:59
2         0 days 00:27:36
3         0 days 00:15:13
4         0 days 00:16:32
                ...
1369760   0 days 00:17:28
1369761   0 days 00:30:00
1369762   0 days 00:16:00
1369763   0 days 00:22:00
1369764   0 days 00:12:00
Name: difference_in_time, Length: 1369765, dtype: timedelta64[ns]

In [ ]:
import matplotlib.pyplot as plt

plt.bar(data["total_amount"],data["trip_distance"])
plt.title('Distance V/s Amount')
plt.xlabel('total_amount')
plt.ylabel('trip_distance')
plt.show()

Most of the data available in CSV is already in prepared form. The required columns have been added and data is cleaned for data loading. Due to size of the data it cannot be uploaded on github hence providing below link for csv file (yellow_tripdata_2021-01.csv) [https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page].